config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :bookers

 get 'bookers' =>'bookers#index', as: 'books'
    post 'bookers' => 'bookers#create'
    get 'bookers/:id' => 'bookers#show', as: 'show_book'
    # get 'bookers/:id' => 'bookers#show', as: 'book'
    get 'bookers/:id/edit' => 'bookers#edit', as: 'edit_book'
    patch 'bookers/:id' => 'bookers#update', as: 'update_book'
    put 'bookers/:id' => 'bookers#update'
    delete 'bookers/:id' => 'bookers#destroy'

get 'bookers/success' => 'bookers#success', as:'success_book'
get 'bookers/error' => 'bookers#error', as:'error_book'

  # get 'top' => 'bookers#top'
  root 'bookers#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController

  def top
# 処理無し
  end

  def index
    @books = Book.all.order("id")
    @book = Book.new
  end

def create
  book = Book.new(book_params)
  if book.save
redirect_to success_book_path
  else
render error_book_path
  end

end

  def show
    @book = Book.find(params[:id])
  end

def update
  book = Book.find(params[:id])

  if  book.update(book_params)
    render success_book_path
  else
    render error_book_path
  end

end
  # def new

  # end

  def edit
      @book = Book.find(params[:id])
  end

def destroy
  book = Book.find(params[:id])
  book.destroy
end

def success

end

def error

end

   private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/views/bookers/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model:@book,url:"/bookers/#{@book.id}" , local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>
<br>
<%= f.submit 'Update Book' %>

<% end %>

<%= link_to 'Show',show_book_path %> | <%= link_to 'Back',bookers_path %>

app/views/bookers/error.html.erb
<h1>Error</h1>
<p>Your request has been false.</p>
<%= link_to '一覧へ戻る',bookers_path %>

app/views/bookers/index.html.erb
<h1>Books</h1>


<table>
  <tbody>
    <% @books.each do |book| %>

    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>

      <td><%= link_to 'Show', show_book_path(book.id) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', bookers_path %></td>
      <td></td>

    </tr>

    <% end %>
  </tbody>


</table>

<h2>New Book</h2>

<%= form_with model:@book, local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>
<br>
<%= f.submit 'Create Book' %>

<% end %>

app/views/bookers/new.html.erb
<h1>Bookers#new</h1>
<p>Find me in app/views/bookers/new.html.erb</p>

app/views/bookers/show.html.erb
<h1>Profile</h1>
<h2>Title</h2>
<%= @book.title %>
<h2>Body</h2>
<%= @book.body %>

app/views/bookers/success.html.erb
<h1>Success</h1>
<p>Your request has been successfully completed.</p>
<%= link_to '一覧へ',bookers_path %>

app/views/bookers/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p>
 <%= link_to 'Start', bookers_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>